wwwContentManager/Models/DeviceGroup.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace wwwContentManager.Models
{
    public class DeviceGroup
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Device> Devices { get; set; }
        public virtual ICollection<File> Contents { get; set; }
    }
}

wwwContentManager/Controllers/DeviceGroupController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using wwwContentManager.Models;
using wwwContentManager.Services;

namespace wwwContentManager.Controllers
{
    public class DeviceGroupController : Controller
    {
        ApplicationDbContext Db = new ApplicationDbContext();

        public ActionResult Index()
        {
            return View(Db.DeviceGroups.ToList());
        }

        public ActionResult Create()
        {
            var model = new CreateDeviceGroupViewModel();
            var devices = Db.Devices.ToList();
            model.DeviceGroup = new DeviceGroup();
            model.Devices = new List<DeviceViewModel>();
            for (int i = 0; i < devices.Count; i++)
            {
                var item = new DeviceViewModel();
                item.Selected = false;
                item.Name = devices[i].Name;
                item.Id = devices[i].Id;
                model.Devices.Add(item);
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(CreateDeviceGroupViewModel group)
        {
            var newGroup = new DeviceGroup();
            newGroup.Name = group.DeviceGroup.Name;
            foreach (var device in group.Devices)
            {
                if (device.Selected)
                {
                    var item = Db.Devices.Find(device.Id);
                    newGroup.Devices.Add(item);
                    item.DeviceGroups.Add(newGroup);
                    Db.Entry(item).State = EntityState.Modified;
                }
            }
            Db.DeviceGroups.Add(newGroup);
            Db.Entry(newGroup).State = EntityState.Added;
            Db.SaveChanges();
            return Redirect("Index");
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DeviceGroup group = Db.DeviceGroups.Find(id);
            if (group == null)
            {
                return HttpNotFound();
            }
            return View(group);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DeviceGroup device = Db.DeviceGroups.Find(id);
            if (device == null)
            {
                return HttpNotFound();
            }
            return View(device);
        }

        [HttpPost]
        public ActionResult Edit(DeviceGroup group)
        {
            if (ModelState.IsValid)
            {
                Db.Entry(group).State = EntityState.Modified;
                Db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(group);
        }

        public ActionResult Delete(int id)
        {
            DeviceGroup device = Db.DeviceGroups.Find(id);
            Db.DeviceGroups.Remove(device);
            Db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult SendContent(int id)
        {
            var files = Db.Files.ToList();
            var isSelected = new List<bool>();
            var intervals = new List<int>();
            foreach (var file in files)
            {
                isSelected.Add(false);
                intervals.Add(10);
            }

            var viewModel = new GroupSendContentViewModel()
            {
                Files = files,
                IsSelected = isSelected,
                GroupId = id,
                Date = DateTime.Now,
                DateEnd = DateTime.Now,
                ImageDisplayInterval = intervals
            };
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult SendContent(GroupSendContentViewModel model)
        {
            var files = Db.Files.ToList();
            var devices = Db.DeviceGroups.Include(x => x.Devices).Where(x => x.Id == model.GroupId).FirstOrDefault().Devices.ToList();
            var playlists = new List<Playlist>();
            for (int i = 0; i < devices.Count; i++)
            {
                var playlist = new Playlist() { DisplayDateTime = model.Date, EndDateTime = model.DateEnd, DeviceId = devices[i].Id };
                playlist.Queue = new List<Package>();
                Boolean sendingContent = false;
                Functions func = new Functions();
                var contentToDisplay = new List<File>();
                for (int j = 0; j < model.IsSelected.Count; j++)
                {
                    if (model.IsSelected[j])
                    {
                        var pack = new Package() { ImageDisplayInterval = model.ImageDisplayInterval[j], ContentToDisplay = files[j] };
                        playlist.Queue.Add(pack);
                        Db.Packages.Add(pack);
                        Db.Entry(pack).State = EntityState.Added;
                    }
                }

                Db.Playlists.Add(playlist);
                Db.Entry(devices[i]).State = EntityState.Modified;
                Db.SaveChanges();
                new Task(() =>
                {
                    sendingContent = func.sendCommand(deviceCommands.SEND_NEW_CONTENT, devices[i].Ip);
                }).Start();
            }
            return RedirectToAction("Index");
        }
    }
}

wwwContentManager/Views/DeviceGroup/Create.cshtml
@model wwwContentManager.Models.CreateDeviceGroupViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Dodaj grupe</h2>
@using (Html.BeginForm("Create", "DeviceGroup"))
{
    <div class="form-group">
        @Html.Label("Nazwa")
        @Html.TextBoxFor(model => model.DeviceGroup.Name, new { @class = "form-control" })
    </div>
    <table class="table table-striped">
        @Html.HiddenFor(m => Model.Devices)
    @foreach (var item in Model.Devices)
    {
        <tr>
            <td>@Html.CheckBoxFor(m => item.Selected)</td>
            <td>@Html.DisplayFor(m => item.Name)</td>
            <td>@Html.DisplayFor(m => item.Ip)</td>
        </tr>
    }
    </table>
    <button type="submit" class="btn btn-default">Dodaj</button>
}

wwwContentManager/Views/DeviceGroup/Details.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div>
    
    </div>
</body>
</html>

wwwContentManager/Views/DeviceGroup/Edit.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div>
    
    </div>
</body>
</html>

wwwContentManager/Views/DeviceGroup/Index.cshtml
@model IEnumerable<wwwContentManager.Models.DeviceGroup>

@{
    ViewBag.Title = "Lista grup";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>
<div class="row">
    @Html.ActionLink("Add new group", "Create", "DeviceGroup", new { @class = "btn btn-default" })
</div>
<div class="row" style="margin-top: 30px;">
    <table class="table table-striped">
        <tr>
            <th>Id</th>
            <th>Nazwa</th>
            <td>Akcja</td>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td>
                    @Html.ActionLink("Wyślij multimedia", "SendContent", "DeviceGroup", new { id = item.Id }, new { @class = "btn btn-sm btn-success", @style = "margin-right: 15px;" })
                    @Html.ActionLink("Info", "Details", "DeviceGroup", new { id = item.Id }, new { @class = "btn btn-sm btn-info" })
                    @Html.ActionLink("Edytuj", "Edit", "DeviceGroup", new { id = item.Id }, new { @class = "btn btn-sm btn-default" })
                    @Html.ActionLink("Usuń", "Delete", "DeviceGroup", new { id = item.Id }, new { @class = "btn btn-sm btn-danger" })
                </td>
            </tr>
        }
    </table>
</div>

wwwContentManager/Views/DeviceGroup/SendContent.cshtml
@model wwwContentManager.Models.GroupSendContentViewModel

@{
    ViewBag.Title = "Wybierz element do wysłania do grupy";
}
<h2>@ViewBag.Title</h2>
<h3>@ViewBag.Message</h3>
<div class="row" style="margin-top: 30px;">
    @using (Html.BeginForm("SendContent", "DeviceGroup"))
    {
        @Html.HiddenFor(m => m.Files)
        @Html.HiddenFor(m => m.GroupId)
        <table class="table table-hover table-striped">
            @for (int i = 0; i < Model.Files.Count; i++)
            {
                <tr>
                    <td>@Html.CheckBoxFor(m => m.IsSelected[i])</td>
                    <td>@Model.Files[i].FileName</td>
                    <td>@Html.TextBoxFor(m => m.ImageDisplayInterval[i])</td>
                    <td>Image/Video</td>
                </tr>
            }
        </table>
        <div class="form-group">
            @Html.LabelFor(m => m.Date)
            @Html.TextBoxFor(m => m.Date, new { @class = "form-control", @type = "datetime-local" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Date)
            @Html.TextBoxFor(m => m.DateEnd, new { @class = "form-control", @type = "datetime-local" })
        </div>
        <button type="submit" class="btn btn-default">Dodaj</button>
    }
</div>