wwwContentManager/Models/Device.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace wwwContentManager.Models
{
    public class Device
    {
        public int Id { get; set; }
        public string IMEI { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Type { get; set; }
        public string Ip { get; set; }
        public int Port { get; set; }
        public bool Synchronized { get; set; }

        public virtual ICollection<Package> Packages { get; set; }
        public virtual ICollection<DeviceGroup> DeviceGroups { get; set; }
    }
}

wwwContentManager/Controllers/DevicesController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Sockets;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;
using wwwContentManager.Models;
using wwwContentManager.Services;

namespace wwwContentManager.Controllers
{
    public class DevicesController : Controller
    {
        ApplicationDbContext Db = new ApplicationDbContext();
        Functions FunctionsObj = new Functions();

        public ActionResult Index()
        {
            var devices = Db.Devices.ToList();
            Functions func = new Functions();
            var statuses = FunctionsObj.pingDevices(devices);
            for (int i = 0; i < devices.Count; i++)
            {
                devices[i].Synchronized = statuses[i];
            }
            return View(devices);
        }

        public ActionResult PingTest()
        {
            Functions func = new Functions();
            List<Device> deviceList = Db.Devices.ToList();
            List<Boolean> statuses = func.pingDevices(deviceList);
            return this.Json(statuses, JsonRequestBehavior.AllowGet);
        }

        public ActionResult SendCommandTest()
        {
            Functions func = new Functions();
            func.sendCommand(deviceCommands.SEND_ARE_YOU_OKAY, "192.168.120.101");
            return View();
        }

        public ActionResult SendMessage(string message)
        {

            try
            {
                int portNumber = 5000;
                string serverIP = "192.168.1.7";
                var tcpClient = new TcpClient(serverIP, portNumber);
                var newStream = tcpClient.GetStream();
                var bytesToSend = ASCIIEncoding.ASCII.GetBytes(message);
                newStream.Write(bytesToSend, 0, bytesToSend.Length);
                tcpClient.Close();
            }
            catch { }
            return View("index");
            //Tu trzeba połączyć się z urządzeniem i wysłać mu wiadomosc
        }

        public bool CheckStatus(int id)
        {
            //pingiem sprawdzić czy odpowiada. Jeśli tak to true, inaczej false
            return true;
        }

        //CRUD
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Device machine)
        {
            machine.Synchronized = true;
            Db.Devices.Add(machine);
            Db.SaveChanges();
            return Redirect("Index");
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Device machine = Db.Devices.Find(id);
            if (machine == null)
            {
                return HttpNotFound();
            }
            return View(machine);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Device device = Db.Devices.Find(id);
            if (device == null)
            {
                return HttpNotFound();
            }
            return View(device);
        }

        [HttpPost]
        public ActionResult Edit(Device machine)
        {
            if (ModelState.IsValid)
            {
                Db.Entry(machine).State = EntityState.Modified;
                Db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(machine);
        }

        public ActionResult Delete(int id)
        {
            Device device = Db.Devices.Find(id);
            Db.Devices.Remove(device);
            Db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                Db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult ReadDevice(int id)
        {
            return View();
        }

        public ActionResult SendContent(int id)
        {
            var files = Db.Files.ToList();
            var isSelected = new List<bool>();
            var intervals = new List<int>();
            foreach (var file in files)
            {
                isSelected.Add(false);
                intervals.Add(10);
            }

            var viewModel = new DeviceSendContentViewModel()
            {
                Files = files,
                IsSelected =isSelected,
                DeviceId = id,
                Date = DateTime.Now,
                DateEnd = DateTime.Now,
                ImageDisplayInterval = intervals
            };
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult SendContent(DeviceSendContentViewModel model)
        {
            var files = Db.Files.ToList();
            var device = Db.Devices.Find(model.DeviceId);
            var playlist = new Playlist() { DisplayDateTime = model.Date, EndDateTime = model.DateEnd, DeviceId = device.Id };
            playlist.Queue = new List<Package>();
            Boolean sendingContent = false;
            Functions func = new Functions();
            var contentToDisplay = new List<File>();
            for (int i = 0; i < model.IsSelected.Count; i++)
            {
                if (model.IsSelected[i])
                {
                    var pack = new Package() { ImageDisplayInterval = model.ImageDisplayInterval[i], ContentToDisplay = files[i] };
                    playlist.Queue.Add(pack);
                    Db.Packages.Add(pack);
                    Db.Entry(pack).State = EntityState.Added;
                }
            }

            Db.Playlists.Add(playlist); 
            Db.Entry(device).State = EntityState.Modified;
            Db.SaveChanges();
            new Task(() => {
                sendingContent = func.sendCommand(deviceCommands.SEND_NEW_CONTENT, device.Ip);
            }).Start();
            return RedirectToAction("Index");
        }
    }
}

wwwContentManager/Views/Devices/Create.cshtml
@model wwwContentManager.Models.Device

@{
    ViewBag.Title = "Create";
}

<h2>Dodaj</h2>
@using (Html.BeginForm("Create", "Devices"))
{
    <div class="form-group">
        @Html.Label("Nazwa")
        @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.Label("Ip")
        @Html.TextBoxFor(model => model.Ip, new { @class = "form-control"})
    </div>
    <div class="form-group">
        @Html.Label("IMEI")
        @Html.TextBoxFor(model => model.IMEI, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.Label("Opis")
        @Html.TextBoxFor(model => model.Description, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.Label("Typ")
        @Html.TextBoxFor(model => model.Type, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.Label("Port")
        @Html.TextBoxFor(model => model.Port, new { @class = "form-control" })
    </div>
    <button type="submit" class="btn btn-default">Dodaj</button>
}

wwwContentManager/Views/Devices/Details.cshtml
@model wwwContentManager.Models.Device

@{
    ViewBag.Title = "Details";
}

<h2>Info</h2>
<div class="form-group">
    @Html.Label("Nazwa")
    @Html.TextBoxFor(model => model.Name, new { @class = "form-control", @ViewBag.Disabled })
</div>
<div class="form-group">
    @Html.Label("Ip")
    @Html.TextBoxFor(model => model.Ip, new { @class = "form-control", @ViewBag.Disabled })
</div>
<div class="form-group">
    @Html.Label("IMEI")
    @Html.TextBoxFor(model => model.IMEI, new { @class = "form-control", @ViewBag.Disabled })
</div>
<div class="form-group">
    @Html.Label("Opis")
    @Html.TextBoxFor(model => model.Description, new { @class = "form-control", @ViewBag.Disabled })
</div>
<div class="form-group">
    @Html.Label("Typ")
    @Html.TextBoxFor(model => model.Type, new { @class = "form-control", @ViewBag.Disabled })
</div>
<div class="form-group">
    @Html.Label("Port")
    @Html.TextBoxFor(model => model.Port, new { @class = "form-control", @ViewBag.Disabled })
</div>

wwwContentManager/Views/Devices/Edit.cshtml
@model wwwContentManager.Models.Device

@{
    ViewBag.Title = "Edit";
}

<h2>Edycja</h2>
@using (Html.BeginForm("Edit", "Devices"))
{
    <div class="form-group">
        @Html.Label("Nazwa")
        @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.Label("Ip")
        @Html.TextBoxFor(model => model.Ip, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.Label("IMEI")
        @Html.TextBoxFor(model => model.IMEI, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.Label("Opis")
        @Html.TextBoxFor(model => model.Description, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.Label("Typ")
        @Html.TextBoxFor(model => model.Type, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.Label("Port")
        @Html.TextBoxFor(model => model.Port, new { @class = "form-control" })
    </div>
    <button type="submit" class="btn btn-default">Edytuj</button>
}

wwwContentManager/Views/Devices/Index.cshtml
@model IEnumerable<wwwContentManager.Models.Device>

@{
    ViewBag.Title = "Lista urządzeń";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>
<div class="row">
    @Html.ActionLink("Add new device", "Create", "Devices", new { @class = "btn btn-default" })
    @Html.ActionLink("Check statuses", "Index", "Devices", new { @class = "btn btn-info" })
</div>
<div class="row" style="margin-top: 30px;">
    @using (Html.BeginForm("SendMessage", "Devices"))
    {
    <table class="table table-striped">
        <tr>
            <th>Id</th>
            <th>Nazwa</th>
            <th>Adres IP</th>
            <th>Status</th>
            <td>Akcja</td>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td>@item.Ip</td>
                <td>
                    @if (item.Synchronized)
                    {
                        <span class="label label-success">Online</span>
                    }
                    else
                    {
                        <span class="label label-danger">Offline</span>
                    }
                </td>
                <td>
                    @Html.ActionLink("Wyślij multimedia", "SendContent", "Devices", new { id = item.Id }, new { @class = "btn btn-sm btn-success", @style = "margin-right: 15px;"})
                    @Html.ActionLink("Info", "Details", "Devices", new { id = item.Id }, new { @class = "btn btn-sm btn-info" })
                    @Html.ActionLink("Edytuj", "Edit", "Devices", new { id = item.Id }, new { @class = "btn btn-sm btn-default" })
                    @Html.ActionLink("Usuń", "Delete", "Devices", new { id = item.Id }, new { @class = "btn btn-sm btn-danger" })
                </td>
            </tr>
        }
    </table>
    }
</div>

wwwContentManager/Views/Devices/SendContent.cshtml
@model wwwContentManager.Models.DeviceSendContentViewModel

@{
    ViewBag.Title = "Wybierz element do wysłania do urządzenia";
}
<h2>@ViewBag.Title</h2>
<h3>@ViewBag.Message</h3>
<div class="row" style="margin-top: 30px;">
    @using (Html.BeginForm("SendContent", "Devices"))
    {
        @Html.HiddenFor(m => m.Files)
        @Html.HiddenFor(m => m.DeviceId)
        <table class="table table-hover table-striped">
        @for(int i = 0; i < Model.Files.Count; i++)
        {
            <tr>
                <td>@Html.CheckBoxFor(m => m.IsSelected[i])</td>
                <td>@Model.Files[i].FileName</td>
                <td>@Html.TextBoxFor(m => m.ImageDisplayInterval[i])</td>
                <td>Image/Video</td>
            </tr>
        }
        </table>
        <div class="form-group">
            @Html.LabelFor(m => m.Date)
            @Html.TextBoxFor(m => m.Date, new { @class = "form-control", @type = "datetime-local" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Date)
            @Html.TextBoxFor(m => m.DateEnd, new { @class = "form-control", @type = "datetime-local" })
        </div>
        <button type="submit" class="btn btn-default">Dodaj</button>
    }
</div>