wwwContentManager/Controllers/GalleryController.cs
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using wwwContentManager.Models;
using Newtonsoft.Json;
using System.Net;
using System.Net.Sockets;
using System.Web;
using System;

namespace wwwContentManager.Controllers
{
    public class GalleryController : Controller
    {
        ApplicationDbContext Db = new ApplicationDbContext();

        public ActionResult Index()
        {
            return View(Db.Files.ToList());
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(HttpPostedFileBase file)
        {
            if (file != null && file.ContentLength > 0)
            {
                var fileName = Path.GetFileName(file.FileName);
                var path = Path.Combine(Server.MapPath("~/Upload/"), fileName);
                file.SaveAs(path);
                var workItem = new Models.File();
                workItem.FileName = Path.GetFileNameWithoutExtension(fileName);
                workItem.FileExtension = Path.GetExtension(fileName);
                Db.Files.Add(workItem);
                Db.SaveChanges();
            }
            return Redirect("Index");
        }

        public ActionResult DonloadById(int id)
        {
            var file = Db.Files.Find(id);
            Response.ContentType = "image/jpeg";
            Response.AppendHeader("Content-Disposition", "attachment; filename=" + file.FileName + file.FileExtension);
            Response.TransmitFile(Server.MapPath("~/Upload/" + file.FileName+file.FileExtension));
            Response.End();
            return RedirectToAction("");
        }

        public string Download(string id)
        {
            var device = Db.Devices.Where(d => d.IMEI == id).FirstOrDefault();
            var playlists = Db.Playlists.Where(x => x.DeviceId == device.Id && x.DisplayDateTime >= DateTime.Now);

            var host = GetIPAddress();
            var downloadPlaylists = new List<DownloadPlaylistViewModel>();
            if (playlists != null)
            {
                foreach (var playlist in playlists)
                {
                    var downloadPlaylist = new DownloadPlaylistViewModel()
                    {
                        Id = playlist.Id,
                        DisplayDateTime = playlist.DisplayDateTime,
                        EndDateTime = playlist.EndDateTime,
                        Queue = new List<DownloadPackageViewModel>()
                    };
                    for (int i = 0; i < playlist.Queue.Count; i++)
                    {
                        var downloadFile = new DownloadFileViewModel()
                        {
                            Id = playlist.Queue.ToList()[i].ContentToDisplay.Id,
                            FileName = playlist.Queue.ToList()[i].ContentToDisplay.FileName,
                            FileExtension = playlist.Queue.ToList()[i].ContentToDisplay.FileExtension,
                            ServerIp = host
                        };
                        var downloadPackage = new DownloadPackageViewModel()
                        {
                            Id = playlist.Queue.ToList()[i].Id,
                            ImageDisplayInterval = playlist.Queue.ToList()[i].ImageDisplayInterval,
                            ContentToDisplay = downloadFile
                        };
                        downloadPlaylist.Queue.Add(downloadPackage);
                    }
                    downloadPlaylists.Add(downloadPlaylist);
                }
                return JsonConvert.SerializeObject(downloadPlaylists);
            }    
            return "";
        }

        protected string GetIPAddress()
        {
            System.Web.HttpContext context = System.Web.HttpContext.Current;
            string ipAddress = context.Request.ServerVariables["HTTP_X_FORWARDED_FOR"];

            if (!string.IsNullOrEmpty(ipAddress))
            {
                string[] addresses = ipAddress.Split(',');
                if (addresses.Length != 0)
                {
                    return addresses[0];
                }
            }

            return context.Request.ServerVariables["REMOTE_ADDR"];
        }
    }
}

wwwContentManager/Views/Gallery/Create.cshtml
@model wwwContentManager.Models.FileViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Dodaj</h2>
@using (Html.BeginForm("Create", "Gallery", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="form-group">
        @Html.Label("Plik")
        @Html.TextBoxFor(model => model.File, null, new { type = "file", @class = "form-control" })
    </div>
    <button type="submit" class="btn btn-default">Dodaj</button>
}

wwwContentManager/Views/Gallery/Index.cshtml
@model IEnumerable<wwwContentManager.Models.File>

@{
    ViewBag.Title = "Galeria";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>
<div class="row">
    @Html.ActionLink("Add new content", "Create", "Gallery", new { @class = "btn btn-default" })
</div>
<div class="row" style="margin-top: 30px;">
    <table class="table table-striped">
        <tr>
            <th>Id</th>
            <th>Nazwa</th>
            <th>Typ</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@Html.ActionLink(item.FileName, "DonloadById/"+item.Id, "Gallery")</td>
                <td>@item.FileExtension</td>
            </tr>
        }
    </table>
</div>